PraslaBonnerWondwossenFinalProject/PraslaBonnerWondwossenFinalProject/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PraslaBonnerWondwossenFinalProject.Models;
using Microsoft.AspNet.Identity;
using System.Web.Security;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;

namespace PraslaBonnerWondwossenFinalProject.Controllers
{
    public class CustomersController : Controller
    {
        private AppDbContext db = new AppDbContext();
        [Authorize(Roles = "Customer")]
        public ActionResult Index()
        {
            AppUser AppUser = db.Users.Find(User.Identity.GetUserId());
            if (AppUser.BankAccounts.Contains(null)) {
                AppUser.BankAccounts.Remove(null);
            }
            if (AppUser.BankAccounts.Count() == 0)
            {
                ViewBag.hasAccounts = false;
            }
            else {
                ViewBag.hasAccounts = true;
            }
            
            return View(AppUser);
        }

        // GET: Customers
        public ActionResult List()
        {
            List<AppUser> appUsers = new List<AppUser>();
            appUsers = db.Users.ToList();
            List<AppUser> customers = new List<AppUser>();
            AppUserManager man = new AppUserManager(new UserStore<AppUser>(db));
            foreach (var item in appUsers) {
                if (man.IsInRole(item.Id, "Customer")){
                    customers.Add(item);       
                }
            }
            //bool to see if uses is in a certain role: User.IsInRole("Customer")
            return View(customers);
            //return View(db.Users.ToList());
        }

        // GET: persons/Edit/5
        [Authorize(Roles = "Customer,Manager,Employee")]
        public ActionResult Edit()

        {

                string id = User.Identity.GetUserId();
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                AppUser user = db.Users.Find(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                if (user.Id != User.Identity.GetUserId() && !User.IsInRole("Admin"))
                {
                    return RedirectToAction("Login", "Account");
                }
                return View(user);
        }

        //edit from employee or manager
        //TODO: add authorization for managers and employees 

        
        public ActionResult EmployeeEdit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppUser customer = db.Users.Find(id);
            if (customer==null)
            {
                return HttpNotFound();
            }
            return View("Edit",customer);
        }




        // POST: persons/Edit/5


        //Customers/Edits allows users to update their own profiles or employees/managers to edit customers

        //TODO:allow employees to make customer inactive
        //TODO: Isn't saving
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FName,LName,Middle,Email,PhoneNumber,Address,City,State,Zip,Birthday")] AppUser person)
        {
            if (ModelState.IsValid)
            {

                //Find associated person
                AppUser personToChange = db.Users.Find(User.Identity.GetUserId());

               
              


                    //update the rest of the fields
                    personToChange.FName = person.FName;
                    personToChange.LName = person.LName;
                    personToChange.Middle = person.Middle;
                    personToChange.Address = person.Address;
                    personToChange.City = person.City;
                    personToChange.State = person.State;
                    personToChange.Zip = person.Zip;
                    personToChange.PhoneNumber = person.PhoneNumber;
                    personToChange.Email = person.Email;
                    personToChange.Birthday = person.Birthday;
                    db.Entry(personToChange).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
               
            }
            return View(person);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EmployeeEdit([Bind(Include = "Id,FName,LName,Middle,Email,PhoneNumber,Address,City,State,Zip,Birthday,isActive")] AppUser person)
        {
            if (ModelState.IsValid)
            {

                //Find associated person
                AppUser personToChange = db.Users.Find(person.Id);
 
                //update the rest of the fields
                personToChange.FName = person.FName;
                personToChange.LName = person.LName;
                personToChange.Middle = person.Middle;
                personToChange.Address = person.Address;
                personToChange.City = person.City;
                personToChange.State = person.State;
                personToChange.Zip = person.Zip;
                personToChange.PhoneNumber = person.PhoneNumber;
                personToChange.Email = person.Email;
                personToChange.Birthday = person.Birthday;
                personToChange.isActive = person.isActive;

                db.Entry(personToChange).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");

            }
            return View(person);
        }
         


        //TODO: make so 
        public ActionResult Details(string Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppUser user = db.Users.Find(Id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        
    }
}

PraslaBonnerWondwossenFinalProject/PraslaBonnerWondwossenFinalProject/Controllers/StockController.cs
using System;

using System.Collections.Generic;

using System.Linq;

using System.Web;

using System.Web.Mvc;

using PraslaBonnerWondwossenFinalProject.Models;

using PraslaBonnerWondwossenFinalProject.StockUtilities;

using Microsoft.AspNet.Identity;

using System.Net;


namespace PraslaBonnerWondwossenFinalProject.Controllers

{

    public class StockController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: Home

        public ActionResult Index()

        {

            List<StockQuote> Quotes = new List<StockQuote>();

            StockQuote sq1 = GetQuote.GetStock("AAPL");
            Quotes.Add(sq1);


            StockQuote sq2 = GetQuote.GetStock("GOOG");
            Quotes.Add(sq2);


            StockQuote sq3 = GetQuote.GetStock("AMZN");
            Quotes.Add(sq3);


            StockQuote sq4 = GetQuote.GetStock("LUV");
            Quotes.Add(sq4);



            StockQuote sq5 = GetQuote.GetStock("TXN");
            Quotes.Add(sq5);



            StockQuote sq6 = GetQuote.GetStock("HSY");
            Quotes.Add(sq6);


            StockQuote sq7 = GetQuote.GetStock("V");
            Quotes.Add(sq7);


            StockQuote sq8 = GetQuote.GetStock("NKE");
            Quotes.Add(sq8);

            StockQuote sq9 = GetQuote.GetStock("VWO");
            Quotes.Add(sq9);

            StockQuote sq10 = GetQuote.GetStock("CORN");
            Quotes.Add(sq10);


            StockQuote sq11 = GetQuote.GetStock("OBMCX");
            Quotes.Add(sq11);


            StockQuote sq12 = GetQuote.GetStock("F");
            Quotes.Add(sq12);


            StockQuote sq13 = GetQuote.GetStock("BAC");
            Quotes.Add(sq13);



            StockQuote sq14 = GetQuote.GetStock("VNQ");
            Quotes.Add(sq14);



            StockQuote sq15 = GetQuote.GetStock("NDX");
            Quotes.Add(sq15);


            StockQuote sq16 = GetQuote.GetStock("KMX");
            Quotes.Add(sq16);


            StockQuote sq17 = GetQuote.GetStock("DIA");
            Quotes.Add(sq17);

            StockQuote sq18 = GetQuote.GetStock("SPY");
            Quotes.Add(sq18);

            StockQuote sq19 = GetQuote.GetStock("BEN");
            Quotes.Add(sq19);

            StockQuote sq20 = GetQuote.GetStock("PGSCX");
            Quotes.Add(sq20);

            return View(Quotes);

        }

        //Jessica --what to use instead of db?

        // GET: stocks/Create
        public ActionResult Purchase()
        {
            ViewBag.AllStocks = GetAllStocks();
            ViewBag.AllAccounts = GetAllAccounts();
            return View();
        }

        //POST: stocks/Create
        //To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Purchase([Bind(Include = "Id,Shares,Date")] PurchasedStock stock, Int32 StockID, Int32 BankAccountID)
        {
            //get customer
            AppUser customer = db.Users.Find(User.Identity.GetUserId());
            //get purchased stock
            Stock FoundStock = db.Stocks.Find(StockID);
            //get bank acount to get money from
            BankAccount Account = db.BankAccounts.Find(BankAccountID);

            stock.InitialPrice = Convert.ToDecimal(GetQuote.GetStock(FoundStock.Symbol, DateTime.Parse(Convert.ToString(stock.Date))).LastTradePrice);

            //cash Balance of 0
            if (FoundStock.Fees > customer.StockPortfolio.CashBalance)
            {
                return View("Error");
            }

            //check to see if customer selected a stock portfolio
            if (Account.Type==AccountTypes.Stock)
            {
                //if so, see if balance is adequate
                if((Convert.ToDecimal(stock.Shares * Convert.ToDecimal(GetQuote.GetStock(FoundStock.Symbol,DateTime.Parse(Convert.ToString(stock.Date))).LastTradePrice)))>customer.StockPortfolio.CashBalance)
                {
                    return View("Error");
                }
                else
                {
                    customer.StockPortfolio.CashBalance = customer.StockPortfolio.CashBalance - (Convert.ToDecimal(stock.Shares * Convert.ToDecimal(GetQuote.GetStock(FoundStock.Symbol, DateTime.Parse(Convert.ToString(stock.Date))).LastTradePrice)));
                }
                
            }
            else
            {
                if ((stock.Shares * Convert.ToDecimal(GetQuote.GetStock(FoundStock.Symbol, DateTime.Parse(Convert.ToString(stock.Date))).LastTradePrice))>Account.Balance)
                {
                    return View("Error");
                }
            }
            if (customer.StockPortfolio.purchasedstocks != null)
            {
                foreach (PurchasedStock item in customer.StockPortfolio.purchasedstocks)
                {
                    if (item.stock.StockID == StockID)
                    {
                        //add purchased shares to existing purchased share number
                        item.Shares = item.Shares + stock.Shares;
                        //add to total fees
                        customer.StockPortfolio.Fees = customer.StockPortfolio.Fees + FoundStock.Fees;
                        //if successful, redirect here, must put adequate spot

                        //create new transaction for Fees
                        Transaction TransactionFees1 = new Transaction();
                        TransactionFees1.Date = stock.Date;
                        TransactionFees1.Type = TransactionTypes.Fee;
                        TransactionFees1.Amount = FoundStock.Fees;
                        TransactionFees1.Description = "Fee: " + FoundStock.Name;
                        TransactionFees1.FromAccount = Account;
                        customer.Transactions.Add(TransactionFees1);
                        db.Transactions.Add(TransactionFees1);
                        db.SaveChanges();

                        //create transaction for withdrawl
                        Transaction TransactionWithdrawl1 = new Transaction();
                        TransactionWithdrawl1.Date = stock.Date;
                        TransactionWithdrawl1.Type = TransactionTypes.Withdrawal;
                        TransactionWithdrawl1.Amount = Convert.ToDecimal(stock.Shares * FoundStock.LastPrice);
                        TransactionWithdrawl1.Description = "Stock Purchase - Account " + Account.AccountNumber;
                        TransactionWithdrawl1.FromAccount = Account;
                        customer.Transactions.Add(TransactionWithdrawl1);
                        db.Transactions.Add(TransactionWithdrawl1);
                        db.SaveChanges();


                        return RedirectToAction("Index", "Customers");
                    }
                }
            }
            
            //stock is not present in the portfolio
            customer.StockPortfolio.Fees = customer.StockPortfolio.Fees + FoundStock.Fees;
            //assign stock to purchased stock
            stock.stock = FoundStock;
            //assign stockp
            stock.stockportfolio = customer.StockPortfolio;
            customer.StockPortfolio.purchasedstocks.Add(stock);

            //create new transaction for Fees
            Transaction TransactionFees = new Transaction();
            TransactionFees.Date = stock.Date;
            TransactionFees.Type = TransactionTypes.Fee;
            TransactionFees.Amount = FoundStock.Fees;
            TransactionFees.Description = "Fee: "+FoundStock.Name;
            TransactionFees.FromAccount = Account;
            customer.Transactions.Add(TransactionFees);
            db.Transactions.Add(TransactionFees);
            db.SaveChanges();

            //create transaction for withdrawl
            Transaction TransactionWithdrawl = new Transaction();
            TransactionWithdrawl.Date = stock.Date;
            TransactionWithdrawl.Type = TransactionTypes.Withdrawal;
            TransactionWithdrawl.Amount = Convert.ToDecimal(stock.Shares * FoundStock.LastPrice);
            TransactionWithdrawl.Description = "Stock Purchase - Account " + Account.AccountNumber;
            TransactionWithdrawl.FromAccount = Account;
            customer.Transactions.Add(TransactionWithdrawl);
            db.Transactions.Add(TransactionWithdrawl);
            db.SaveChanges();

            return RedirectToAction("Index","Customers");

        }

    

        public SelectList GetAllStocks()
        {
            var query = from q in db.Stocks
                        orderby q.Symbol
                        select q;

            List<Stock> allStocks = query.ToList();


            SelectList allStockslist = new SelectList(allStocks, "StockID", "display");

            return allStockslist;
        }

        public SelectList GetAllAccounts()
        {
            AppUser customer = db.Users.Find(User.Identity.GetUserId());
            List<BankAccount> allAccounts = customer.BankAccounts;

            SelectList allAccountsList = new SelectList(allAccounts, "BankAccountID", "Name");

            return allAccountsList;
        }
    }

}

PraslaBonnerWondwossenFinalProject/PraslaBonnerWondwossenFinalProject/Views/Customers/Details.cshtml
@model PraslaBonnerWondwossenFinalProject.Models.AppUser

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Profile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Middle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Middle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    <</dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to Summary", "Index")
</p>

PraslaBonnerWondwossenFinalProject/PraslaBonnerWondwossenFinalProject/Views/Customers/Edit.cshtml
@model PraslaBonnerWondwossenFinalProject.Models.AppUser

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{




        {
    @Html.AntiForgeryToken()
    <h4> Manage Account Details</h4>
    <div class="form-horizontal">
        <h4>Manage Account Details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Middle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Middle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Middle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (User.IsInRole("Employee") || User.IsInRole("Manager"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.isActive, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    //if customer editing themself
    if (User.IsInRole("Customer"))
    {

    @Html.ActionLink("Change Password?", "ChangePassword", "Manage")
    }
}


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

PraslaBonnerWondwossenFinalProject/PraslaBonnerWondwossenFinalProject/Views/Customers/Index.cshtml
@model  PraslaBonnerWondwossenFinalProject.Models.AppUser


@{
    ViewBag.Title = "My Accounts";
}

<h2>Accounts</h2>

<div>
    <hr />
        
    @if (ViewBag.hasAccounts)
    {
    <table class="table table-bordered">
        <tr>
            <th>
                Account Number
            </th>
            <th>
                Account Name
            </th>
            <th>
                Account Type
            </th>
            <th>
                Balance
            </th>
            <th>
                Actions
            </th>
        </tr>
        @foreach (var item in Model.BankAccounts)
        {
            if (item.Type == PraslaBonnerWondwossenFinalProject.Models.AccountTypes.Stock)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.lastFour)</td>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Type)</td>
                    <td>@Html.DisplayFor(modelItem => item.Balance)</td>
                    <td>@Html.ActionLink("Details", "Details", "StockPortfolios", new { }, null) | @Html.ActionLink("Edit Name", "Edit", "BankAccounts", new { id = item.BankAccountID }, null) |  @Html.ActionLink("Buy Stock", "Purchase", "Stock", new { id = item.BankAccountID }, null) | @Html.ActionLink("Sell Stock", "Index", "PurchasedStocks", new { }, null)</td>
                </tr>
            }
            else
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.lastFour)</td>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.Type)</td>
                    <td>@Html.DisplayFor(modelItem => item.Balance)</td>
                    <td>@Html.ActionLink("Details", "Details", "BankAccounts", new { id = item.BankAccountID }, null) | @Html.ActionLink("Edit Name", "Edit", "BankAccounts", new { id = item.BankAccountID }, null)</td>
                </tr>
            }

        }
    </table>
    }
    else{
        <p> You have no Accounts. Would you like to open an account?</p>
    }

</div>

PraslaBonnerWondwossenFinalProject/PraslaBonnerWondwossenFinalProject/Views/Customers/List.cshtml
@model IEnumerable<PraslaBonnerWondwossenFinalProject.Models.AppUser>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Middle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SSN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        
    
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Middle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Zip)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birthday)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SSN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isActive)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "EmployeeEdit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Change Password?", "ManagerChangePassword", new { controller="Manage", id = item.Id }) |
           
    </tr>
}

</table>